version: '3.8'
services:
  milvus:
    image: milvusdb/milvus:v2.2.5
    ports:
      - "19530:19530"
    command: ["milvus", "run", "standalone"]
  minio:
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
  service3:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET=service3
      - EMBEDDING_MODE=local
      - ANALYSIS_SPACY_MODEL=en_core_web_sm
      - ANALYSIS_NUM_TOPICS=5
      - PERPLEXITY_API_URL=https://api.perplexity.ai/v1/answer
      - PERPLEXITY_API_KEY=YOUR_KEY
      - SPOTIFY_CLIENT_ID=
      - SPOTIFY_CLIENT_SECRET=
    ports:
      - "8000:8000"
    depends_on:
      - milvus
      - minio